Repository llddang/todayeat, pull requests merged in 2025-04, with the labels that each got.

#14 Chore/#13 database column change
  src/components/_auth/auth-sign-up-form.tsx
  src/constants/form-schema.constant.ts
  src/lib/apis/auth-server.api.ts
  src/types/DTO/user.dto.ts
Labels: 🌐 Chore

#18 Update README.md
  README.md
Labels: ✨ Feature

#19 Feature/#15 camelize
  src/lib/utils/camelize.util.ts
  src/types/DTO/user.dto.ts
  src/types/common.type.ts
Labels: ✨ Feature

#34 Feature/#30 프로필 수정
  next.config.mjs
  public/test.png
  src/app/my-page/page.tsx
  src/components/_my-page/my-page-edit-profile.tsx
  src/lib/apis/storage.api.ts
  src/types/supabase-bucket.type.ts
Labels: ✨ Feature

#35 Feature/#31 이미지 파일 base64 인코딩
  package.json
  pnpm-lock.yaml
  src/app/meal/post/page.tsx
  src/app/page.tsx
  src/constants/site-map.constant.ts
  src/lib/utils/convert-image-to-base64.util.ts
  src/store/meal-images.store.ts
  src/types/gemini.type.ts
Labels: ✨ Feature

#38 Feature/#37 find password page
  src/app/(auth)/change-password/page.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/update-password/page.tsx
  src/components/_auth/auth-email-form-for-find-password.tsx
  src/components/_auth/auth-update-password-form.tsx
  src/components/commons/error-handler.tsx
  src/constants/public-error-message.constant.ts
  src/constants/site-map.constant.ts
  src/lib/apis/auth-server.api.ts
Labels: ✨ Feature, 📬 API

#41 Setting/#40 folder structure
  src/app/(auth)/(with-header)/change-password/page.tsx
  src/app/(auth)/(with-header)/find-password/page.tsx
  src/app/(auth)/(with-header)/layout.tsx
  src/app/(auth)/(with-header)/sign-up/page.tsx
  src/app/(auth)/(with-header)/update-password/page.tsx
  src/app/(client)/layout.tsx
  src/app/(client)/meal/post/page.tsx
  src/app/(client)/my-page/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layouts/header.tsx
  src/components/layouts/menu-bar.tsx
Labels: ⚙ Setting

#42 Feature/#33 common layout
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/change-password/page.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/update-password/layout.tsx
  src/app/(auth)/update-password/page.tsx
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/post/layout.tsx
  src/app/(client)/post/page.tsx
  src/app/(client)/report/layout.tsx
  src/app/(client)/report/page.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layouts/header-back-button.tsx
  src/components/layouts/header.tsx
  src/components/layouts/menu-bar.tsx
  src/constants/site-map.constant.ts
Labels: ✨ Feature

#51 Feature/#49 이미지 캐러셀 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/_meal/meal-images-carousel.tsx
  src/components/ui/carousel.tsx
Labels: ✨ Feature

#52 Feature/#39 영양소 계산관련 유틸함수
  src/constants/nutrition.constant.ts
  src/lib/utils/nutrition-calculator.util.ts
  src/types/DTO/meal.dto.ts
  src/types/DTO/user.dto.ts
  src/types/nutrition.type.ts
Labels: ✨ Feature

#55 chore:#54 불필요한 주석 정리 및 useEffect문 수정
  src/components/_my-page/my-page-edit-profile.tsx
Labels: 🌐 Chore

#60 Feature/#58 background component
  src/app/layout.tsx
  src/components/layouts/gradient-blur-background.tsx
  tailwind.config.ts
Labels: ✨ Feature

#53 Feature/#44 use funnel
  src/constants/common.constant.ts
  src/lib/hooks/use-funnel.tsx
  src/lib/utils/predicate.util.ts
  src/lib/utils/session-storage.util.ts
Labels: ✨ Feature

#64 Feature/#56 칼로리 통계 컴포넌트
  src/components/_home/macronutrient-box.tsx
  src/components/_home/macronutrient-group.tsx
  src/constants/common.constant.ts
  src/lib/utils/nutrition-calculator.util.ts
  src/types/nutrition.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design

#65 Feature/#62 global font
  public/fonts/WantedSansVariable.woff2
  src/app/layout.tsx
Labels: ✨ Feature, 🎨 Design

#66 Feature/#63 color palette
  tailwind.config.ts
Labels: ⚙ Setting, 🎨 Design

#67 Feature/#61 add user personal info table
  public/illustrations/meal-category-breakfast.svg
  public/illustrations/meal-category-dinner.svg
  public/illustrations/meal-category-lunch.svg
  public/illustrations/meal-category-snack.svg
  src/constants/meal.constant.ts
  src/constants/user-personal-info.constant.ts
  src/lib/apis/user.api.ts
  src/lib/utils/nutrition-calculator.util.ts
  src/types/DTO/meal.dto.ts
  src/types/DTO/user.dto.ts
  src/types/gender.type.ts
  src/types/meal-category.type.ts
  src/types/meal-type.type.ts
  src/types/nutrition.type.ts
  src/types/user-personal-info.type.ts
Labels: ✨ Feature, 📬 API

#70 Feature/#56 칼로리 통계 컴포넌트
  src/app/layout.tsx
  src/components/_home/home-calories-summary-card.tsx
  src/components/_home/home-macronutrient-box.tsx
  src/components/_home/home-macronutrient-group.tsx
  src/constants/common.constant.ts
  src/constants/home.constant.ts
  src/lib/utils/format-number-with-comma.ts
Labels: ✨ Feature, 🎨 Design

#72 Feature/#71 피드백 예시 cta 컴포넌트
  public/icons/information_line.svg
  public/illustration/cta-banner-sparkle.svg
  src/components/_home/home-cta-example-feedback-banner.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design

#73 Feature/#68 register image
  public/icons/close_line.svg
  public/icons/pic_line.svg
  public/illustrations/image-upload.svg
  src/components/_meal/_post/meal-post-add-image-button.tsx
  src/components/_meal/_post/meal-post-add-image-empty-box.tsx
  src/components/_meal/_post/meal-post-add-image-preview-box.tsx
  src/components/_meal/_post/meal-post-add-image-preview-gallery.tsx
  src/components/_meal/_post/meal-post-add-image.tsx
  src/constants/common.constant.ts
  src/constants/meal.constant.ts
  src/lib/apis/storage.api.ts
  src/lib/utils/file.util.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design

#82 Feature/#79 타이포그래피 컴포넌트 구현
  src/components/ui/typography.tsx
  tailwind.config.ts
Labels: ✨ Feature, 💌 리뷰 필요

#87 Hotfix:#86 타이포그래피 프리픽스 변경
  tailwind.config.ts
Labels: 🐞 BugFix

#89 hotfix:#86 타이포그래피 변수명 긴급수정
  src/components/ui/typography.tsx
Labels: 🐞 BugFix

#90 Feature/#85 project background
  src/app/layout.tsx
  src/components/layouts/gradient-blur-background.tsx
  src/components/layouts/main-background.tsx
  tailwind.config.ts
Labels: 🎨 Design, ✅ 리뷰 완료

#81 Feature/#78 button component
  public/icons/right-line-gray-400.svg
  public/icons/right-line-gray-600.svg
  public/icons/right-line-gray-800.svg
  src/components/_auth/auth-sign-up-form.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#76 Feature/#75 ai 피드백 컴포넌트
  public/illustrations/ai-sparkle-1.svg
  public/illustrations/ai-sparkle-2.svg
  public/illustrations/cta-banner-sparkle.svg
  src/components/_home/home-ai-feedback-text.tsx
  src/constants/home.constant.ts
  src/lib/utils/home.util.ts
  src/types/home.type.ts
  src/types/nutrition.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design

#94 Feature/#92 Footer component
  src/app/(home)/page.tsx
  src/components/commons/footer.tsx
Labels: ✨ Feature, ✅ 리뷰 완료

#88 Feature/#80 input 공통 컴포넌트 구현
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#96 Feature/#93 link component
  src/components/commons/button-link.tsx
  src/components/ui/button.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#83 Feature/#69 Gemini를 이용한 이미지 분석 라우트 핸들러
  package.json
  pnpm-lock.yaml
  src/app/api/gemini/route.ts
  src/constants/ai-error-message.constant.ts
  src/constants/env.constant.ts
  src/constants/prompt.constant.ts
  src/lib/apis/analysis-request.api.ts
  src/lib/apis/gemini.api.ts
  src/lib/utils/convert-image-to-base64.util.ts
  src/lib/utils/gemini.util.ts
  src/store/meal-images.store.ts
  src/types/DTO/food_analysis.dto.ts
  src/types/gemini.type.ts
  src/types/supabase-bucket.type.ts
Labels: ✨ Feature, 💌 리뷰 필요

#98 Feature/#97 icon button
  src/components/commons/icon-button.tsx
  tailwind.config.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#95 Feature/#84 textarea
  src/components/commons/textarea.tsx
Labels: ✨ Feature, ✅ 리뷰 완료

#102 Feature/#91 옵션 카드 버튼 컴포넌트
  src/components/commons/option-select-card.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#100 Feature/#99 tabs component
  package.json
  pnpm-lock.yaml
  src/components/ui/tabs.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#103 Feature/#101 tag select item
  src/components/commons/tag-select-item.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#108 Feature/#104 gnb component 레이아웃 적용
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/post/layout.tsx
  src/app/(client)/report/layout.tsx
  src/app/(home)/layout.tsx
  src/components/layouts/global-navigation-bar-item.tsx
  src/components/layouts/global-navigation-bar.tsx
  src/components/layouts/menu-bar.tsx
Labels: ✨ Feature, 💌 리뷰 필요, ✅ 리뷰 완료

#110 Feature/#74 home calendar week
  src/components/_home/home-calendar-week-item.tsx
  src/components/_home/home-calendar-week.tsx
  src/components/commons/circle-progress-bar.tsx
  src/components/commons/client-only.tsx
  src/constants/calendar.constant.ts
  src/lib/apis/meal.api.ts
  src/lib/contexts/calendar.context.tsx
  src/lib/utils/date.util.ts
  src/types/nutrition.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#117 Feature/#116 유저 전역 상태 관리
  src/lib/hooks/use-user-store.ts
  src/store/user-store.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#106 Feature/#69 calories analysis
  src/app/api/gemini/calories-analysis/route.ts
  src/app/api/gemini/food-image-analysis/route.ts
  src/constants/ai-error-message.constant.ts
  src/constants/prompt.constant.ts
  src/lib/apis/analysis-request.api.ts
  src/lib/apis/gemini.api.ts
  src/types/DTO/food_analysis.dto.ts
  src/types/gemini.type.ts
Labels: ✨ Feature, 💌 리뷰 필요, ✅ 리뷰 완료

#120 Feature/#114 calendar component
  package.json
  pnpm-lock.yaml
  public/icons/down-line-gray-400.svg
  public/icons/down-line-gray-600.svg
  public/icons/down-line-gray-800.svg
  src/app/(home)/page.tsx
  src/components/_home/home-calendar-bottom-up-selector.tsx
  src/components/_home/home-calendar-day-label.tsx
  src/components/_home/home-calendar-month-item.tsx
  src/components/_home/home-calendar-month.tsx
  src/components/_home/home-calendar-week-item.tsx
  src/components/_home/home-calendar-week.tsx
  src/components/_home/home-calendar.tsx
  src/components/ui/calendar.tsx
  src/components/ui/drawer.tsx
  src/constants/calendar.constant.ts
  src/lib/contexts/calendar.context.tsx
  src/lib/contexts/dashboard.context.tsx
  src/lib/utils/date.util.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#122 Design/#121 sign in page
  public/google-logo.svg
  public/kakao-logo.svg
  public/logo.svg
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/components/_auth/_sign-in/auth-sign-in-form.tsx
  src/components/_auth/_sign-in/auth-sign-in-with-google-button.tsx
  src/components/_auth/_sign-in/auth-sign-in-with-kakao-button.tsx
  src/components/_auth/auth-sign-in-with-google-button.tsx
  src/components/_auth/auth-sign-in-with-kakao-button.tsx
  src/components/ui/form.tsx
  tailwind.config.ts
Labels: 🎨 Design, ✅ 리뷰 완료

#77 Feature/#59 meal edit card
  public/icons/close_line.svg
  public/icons/delete_2_line.svg
  public/icons/edit_3_line.svg
  src/app/globals.css
  src/components/_home/home-macronutrient-box.tsx
  src/components/_home/home-macronutrient-group.tsx
  src/components/_meal/_post/meal-post-edit-card-title.tsx
  src/components/_meal/_post/meal-post-edit-card.tsx
  src/components/_meal/_post/meal-post-edit-input-field.tsx
  src/components/_meal/_post/meal-post-edit-nutrient-box.tsx
  src/components/_meal/meal-images-carousel.tsx
  src/components/_my-page/my-page-edit-profile.tsx
  src/components/ui/input.tsx
  src/constants/common.constant.ts
  src/constants/nutrition.constant.ts
  src/lib/apis/meal.api.ts
  src/types/nutrition.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#115 Feature/#105 목표 설정 페이지 구현
  package.json
  pnpm-lock.yaml
  public/illustrations/complete-confetti.svg
  public/lottie/ai-loader-bg.json
  public/lottie/ai-loader-star.json
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/my-page/set-goal/page.tsx
  src/components/_set-goal/set-goal-activity-level-step.tsx
  src/components/_set-goal/set-goal-age-step.tsx
  src/components/_set-goal/set-goal-ai-loader-lottie.tsx
  src/components/_set-goal/set-goal-ai-loading-step.tsx
  src/components/_set-goal/set-goal-calculate-step.tsx
  src/components/_set-goal/set-goal-complete.tsx
  src/components/_set-goal/set-goal-funnel.tsx
  src/components/_set-goal/set-goal-gender-step.tsx
  src/components/_set-goal/set-goal-height-step.tsx
  src/components/_set-goal/set-goal-macronutrient-box.tsx
  src/components/_set-goal/set-goal-progress-section.tsx
  src/components/_set-goal/set-goal-purpose-step.tsx
  src/components/_set-goal/set-goal-weight-step.tsx
  src/components/commons/glass-background.tsx
  src/components/ui/form.tsx
  src/constants/form-schema.constant.ts
  src/constants/funnel-schema.constant.ts
  src/constants/set-goal.constant.ts
  src/constants/user-schema.constant.ts
  src/lib/utils/nutrition-calculator.util.ts
  src/types/set-goal.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#126 Feature/#109 header component
  public/icons/back_line.svg
  public/illustrations/default-profile.svg
  src/components/commons/profile-image.tsx
  src/components/layouts/header-back-button.tsx
  src/components/layouts/header-with-profile.tsx
  src/components/layouts/header.tsx
  src/lib/hooks/use-detect-is-scrolled.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, 💌 리뷰 필요, ⚠️ ASAP

#128 Design/#123 sign up page
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/_auth/_sign-up/auth-sign-up-funnel.tsx
  src/components/_auth/_sign-up/auth-sign-up-progress-bar.tsx
  src/components/_auth/_sign-up/auth-sign-up-step-complete.tsx
  src/components/_auth/_sign-up/auth-sign-up-step-email.tsx
  src/components/_auth/_sign-up/auth-sign-up-step-nickname.tsx
  src/components/_auth/_sign-up/auth-sign-up-step-password.tsx
  src/components/_auth/auth-sign-up-form.tsx
  src/constants/funnel-schema.constant.ts
  src/lib/hooks/use-funnel.tsx
  src/middleware.ts
  src/types/sign-up-funnel-type.ts
Labels: 🎨 Design, 💌 리뷰 필요, ✅ 리뷰 완료

#133 Bugfix/#132 목표 설정 빌드 에러
  src/components/_set-goal/set-goal-activity-level-step.tsx
  src/components/_set-goal/set-goal-age-step.tsx
  src/components/_set-goal/set-goal-ai-loading-step.tsx
  src/components/_set-goal/set-goal-height-step.tsx
  src/components/_set-goal/set-goal-weight-step.tsx
Labels: 🐞 BugFix, ⚠️ ASAP, ✅ 리뷰 완료

#131 Feature/#129 home meal result card
  public/icons/edit-4-line.svg
  src/app/(home)/page.tsx
  src/components/_home/home-meal-card-image-preview.tsx
  src/components/_home/home-meal-card-macronutrient.tsx
  src/components/_home/home-meal-card-memo.tsx
  src/components/_home/home-meal-card-time-indicator.tsx
  src/components/_home/home-meal-card-title.tsx
  src/components/_home/home-meal-card.tsx
  src/components/_home/home-meal-container.tsx
  src/components/_home/home-meal-empty-card.tsx
  src/components/_meal/_post/meal-post-edit-card.tsx
  src/components/commons/macronutrient-box.tsx
  src/constants/meal.constant.ts
  src/constants/nutrition.constant.ts
  src/lib/utils/date.util.ts
  src/types/nutrition.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, 💌 리뷰 필요

#137 Design/#135 마이페이지 레이아웃 수정
  src/app/(client)/my-page/(index)/layout.tsx
  src/app/(client)/my-page/(index)/page.tsx
  src/app/(client)/my-page/set-goal/layout.tsx
  src/components/_set-goal/set-goal-ai-loading-step.tsx
Labels: 🎨 Design, ✅ 리뷰 완료

#139 Design/#138 layout
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(client)/my-page/(index)/layout.tsx
  src/app/(client)/my-page/set-goal/layout.tsx
  src/components/layouts/global-navigation-bar.tsx
  src/components/layouts/header-back-button.tsx
  src/components/layouts/header-with-profile.tsx
  src/components/layouts/header.tsx
  tailwind.config.ts
Labels: 🎨 Design, 💌 리뷰 필요

#136 Feature/#134 home page
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/components/_home/home-calendar-bottom-up-selector.tsx
  src/components/_home/home-content.tsx
  src/components/_home/home-macronutrient-group.tsx
  src/components/_home/home-meal-container.tsx
  src/components/commons/cta-example-feedback-banner.tsx
  src/components/ui/calendar.tsx
  src/store/user-store.ts
  src/types/nutrition.type.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#124 Feature/#112 meal post page
  package.json
  pnpm-lock.yaml
  src/app/(client)/meal/post/edit/page.tsx
  src/app/(client)/meal/post/page.tsx
  src/app/(client)/post/page.tsx
  src/components/_meal/_post/meal-post-add-image-button.tsx
  src/components/_meal/_post/meal-post-add-image-form.tsx
  src/components/_meal/_post/meal-post-add-image.tsx
  src/components/_meal/_post/meal-post-contents.tsx
  src/components/_meal/_post/meal-post-modal.tsx
  src/components/ui/alert-dialog.tsx
  src/constants/site-map.constant.ts
  src/lib/apis/analysis-request.api.ts
  src/lib/apis/meal.api.ts
  src/lib/hooks/use-meal-post-modal.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#141 Docs/#130 readme 작성
  README.md
Labels: 📃 Docs

#142 Design/#140 temp report page
  src/app/(client)/report/layout.tsx
  src/app/(client)/report/page.tsx
  src/components/layouts/global-navigation-bar.tsx
Labels: 🎨 Design, ✅ 리뷰 완료

#144 Design/#143 네비게이션 메뉴바 위치 이동
  src/components/layouts/global-navigation-bar.tsx
Labels: 🎨 Design, ✅ 리뷰 완료

#146 Design/#145 home meal card memo
  src/components/_home/home-meal-card-memo.tsx
  src/components/_home/home-meal-card.tsx
  src/lib/apis/meal.api.ts
Labels: 🎨 Design, ✅ 리뷰 완료

#147 Feature/#125 add meal bottomsheet
  public/icons/add_line.svg
  src/app/api/gemini/calories-analysis/route.ts
  src/app/api/meal-post/route.ts
  src/components/_meal/_post/meal-post-add-meal-ai-loading.tsx
  src/components/_meal/_post/meal-post-add-meal-card.tsx
  src/components/_meal/_post/meal-post-add-meal-drawer.tsx
  src/components/_set-goal/set-goal-calculate-step.tsx
  src/components/commons/icon-button.tsx
  src/lib/apis/analysis-request.api.ts
  src/types/DTO/food_analysis.dto.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, 🐱 다은 리뷰중

#149 Feature/#148 목표 설정 미반영 로직 수정
  src/components/_set-goal/set-goal-calculate-step.tsx
  src/lib/utils/revalidate.util.ts
Labels: ✨ Feature

#152 Feature/#150 logo to home
  src/app/(auth)/sign-in/page.tsx
  src/components/layouts/header-with-profile.tsx
  src/components/layouts/header.tsx
Labels: ✨ Feature, 💌 리뷰 필요

#153 Feature/#151 post meal
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/change-password/page.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/update-password/layout.tsx
  src/app/(auth)/update-password/page.tsx
  src/components/_meal/_post/meal-post-add-image-button.tsx
  src/lib/apis/analysis-request.api.ts
Labels: ✨ Feature, 🎨 Design, 💌 리뷰 필요

#155 Fix/ lottie import 경로 수정
  src/components/_meal/_post/meal-post-edit-card.tsx
Labels: 🐞 BugFix, ⚠️ ASAP

#160 Fix/#156 키, 몸무게 입력 폼 소수점도 가능하도록 수정
  src/components/_set-goal/set-goal-height-step.tsx
Labels: 🐞 BugFix, 💌 리뷰 필요

#159 Feature/#157 use user store
  src/app/(client)/my-page/set-goal/page.tsx
  src/app/layout.tsx
  src/components/_home/home-content.tsx
  src/components/_meal/_post/meal-post-add-image-button.tsx
  src/components/_meal/_post/meal-post-add-meal-drawer.tsx
  src/components/_my-page/my-page-edit-profile.tsx
  src/components/_my-page/my-page-profile-bar.tsx
  src/components/_my-page/my-page-setting-card.tsx
  src/components/_set-goal/set-goal-calculate-step.tsx
  src/components/commons/user-initializer.tsx
  src/components/layouts/header-with-profile-layer.tsx
  src/components/layouts/header-with-profile.tsx
  src/lib/hooks/use-user-store.ts
  src/store/user-store.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#161 Feature/#158 식단등록 로딩UI표시하기
  src/app/(client)/meal/post/edit/page.tsx
Labels: ✨ Feature

#163 Refactor/#162 home page
  src/components/_home/home-content.tsx
  src/components/_home/home-meal-card-image-preview.tsx
  src/components/_home/home-meal-card-memo.tsx
  src/components/_home/home-meal-card-time-indicator.tsx
  src/components/_home/home-meal-card-title.tsx
  src/components/_home/home-meal-card.tsx
  src/components/_home/home-meal-container.tsx
  src/components/commons/macronutrient-group.tsx
  src/lib/apis/meal.api.ts
Labels: 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#164 Refactor/#168 post add image
  src/app/(client)/meal/post/components/add-image.tsx
  src/components/_meal/_post/meal-post-add-image-button.tsx
  src/components/_meal/_post/meal-post-add-image-empty-box.tsx
  src/components/_meal/_post/meal-post-add-image-form.tsx
  src/components/_meal/_post/meal-post-add-image-preview-box.tsx
  src/components/_meal/_post/meal-post-add-image-preview-gallery.tsx
  src/components/_meal/_post/meal-post-add-image.tsx
Labels: 🔨 Refactor, ✅ 리뷰 완료

#169 Refactor/#165 도메인 종속성 강화
  src/app/(client)/my-page/components/edit-profile.tsx
  src/app/(client)/my-page/components/macronutrient-card.tsx
  src/app/(client)/my-page/components/profile-bar.tsx
  src/app/(client)/my-page/components/setting-card.tsx
  src/app/(client)/my-page/components/user-goal-card.tsx
  src/app/(client)/my-page/components/user-info-list.tsx
  src/app/(client)/my-page/components/user-physical-info-card.tsx
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/my-page/page.tsx
  src/app/(client)/set-goal/components/ai-loader-lottie.tsx
  src/app/(client)/set-goal/components/macronutrient-box.tsx
  src/app/(client)/set-goal/components/progress-section.tsx
  src/app/(client)/set-goal/components/set-goal-funnel.tsx
  src/app/(client)/set-goal/components/step-activity-level.tsx
  src/app/(client)/set-goal/components/step-age.tsx
  src/app/(client)/set-goal/components/step-ai-loading.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/components/step-complete.tsx
  src/app/(client)/set-goal/components/step-gender.tsx
  src/app/(client)/set-goal/components/step-height.tsx
  src/app/(client)/set-goal/components/step-purpose.tsx
  src/app/(client)/set-goal/components/step-weight.tsx
  src/app/(client)/set-goal/constants/funnel.constant.ts
  src/app/(client)/set-goal/layout.tsx
  src/app/(client)/set-goal/page.tsx
  src/app/(client)/set-goal/types/funnel.type.ts
  src/components/_my-page/my-page-user-info-list.tsx
  src/components/_set-goal/set-goal-activity-level-step.tsx
  src/components/_set-goal/set-goal-funnel.tsx
  src/constants/set-goal.constant.ts
  src/constants/site-map.constant.ts
  src/constants/user-personal-info.constant.ts
  src/lib/utils/get-emoji-for-personal-info.util.ts
Labels: 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#171 Refactor/#167 post edit
  src/app/(client)/meal/post/components/restore-analysis-modal.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/meal/post/edit/components/edit-card.tsx
  src/app/(client)/meal/post/edit/page.tsx
  src/app/(client)/meal/post/hooks/use-restore-analys-modal.ts
  src/app/(client)/meal/post/page.tsx
  src/components/_meal/_post/meal-post-edit-card-title.tsx
  src/components/_meal/_post/meal-post-edit-input-field.tsx
  src/components/commons/textarea.tsx
  src/constants/nutrition.constant.ts
  src/types/nutrition.type.ts
Labels: 🔨 Refactor, 💌 리뷰 필요

#170 Refactor/#166 refactoring layout
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/update-password/layout.tsx
  src/app/(client)/meal/post/layout.tsx
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/post/layout.tsx
  src/app/(client)/report/layout.tsx
  src/app/(client)/set-goal/layout.tsx
  src/app/(home)/layout.tsx
  src/components/_meal/_post/meal-post-add-meal-card.tsx
  src/components/_meal/_post/meal-post-add-meal-drawer.tsx
  src/components/layouts/global-navigation-bar/index.tsx
  src/components/layouts/global-navigation-bar/item.tsx
  src/components/layouts/header-back-button.tsx
  src/components/layouts/header.tsx
  src/components/layouts/header/header-wrapper.tsx
  src/components/layouts/header/variants/header-back-button.tsx
  src/components/layouts/header/variants/header-default.tsx
  src/components/layouts/header/variants/header-with-profile.tsx
Labels: 🔨 Refactor, 💌 리뷰 필요

#179 Refactor/#178 마이페이지 qa 반영
  src/app/(client)/my-page/components/edit-profile.tsx
  src/app/(client)/my-page/components/profile-bar.tsx
  src/components/commons/profile-image.tsx
  src/components/layouts/header/variants/header-with-profile.tsx
Labels: 🎨 Design, 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#186 Design/#185 temp layout 변경
  src/components/layouts/global-navigation-bar/index.tsx
  src/components/layouts/header/header-wrapper.tsx
  tailwind.config.ts
Labels: 🎨 Design, 💌 리뷰 필요, ⚠️ ASAP

#177 Refactor/#175 목표 설정 qa 반영
  src/app/(auth)/sign-up/components/auth-sign-up-funnel.tsx
  src/app/(client)/set-goal/components/set-goal-funnel.tsx
  src/app/(client)/set-goal/components/step-activity-level.tsx
  src/app/(client)/set-goal/components/step-age.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/components/step-gender.tsx
  src/app/(client)/set-goal/components/step-height.tsx
  src/app/(client)/set-goal/components/step-purpose.tsx
  src/app/(client)/set-goal/components/step-weight.tsx
  src/app/(client)/set-goal/page.tsx
  src/app/layout.tsx
  src/components/commons/ai-loader-lottie.tsx
  src/hooks/use-funnel.tsx
Labels: 🎨 Design, 🔨 Refactor, ✅ 리뷰 완료

#187 Design/#182 sign page design qa
  src/app/(auth)/sign-in/components/google-sign-in-button.tsx
  src/app/(auth)/sign-in/components/kakao-sign-in-button.tsx
  src/app/(auth)/sign-in/components/sign-in-form.tsx
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/components/auth-sign-up-funnel.tsx
  src/app/(auth)/sign-up/components/sign-up-funnel.tsx
  src/app/(auth)/sign-up/components/step-complete.tsx
  src/app/(auth)/sign-up/components/step-email.tsx
  src/app/(auth)/sign-up/components/step-nickname.tsx
  src/app/(auth)/sign-up/components/step-password.tsx
  src/app/(auth)/sign-up/constants/set-goal.constant.ts
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/sign-up/types/funnel-type.ts
  src/app/(client)/set-goal/components/progress-section.tsx
  src/app/(client)/set-goal/page.tsx
  src/app/(client)/set-goal/types/funnel.type.ts
  src/components/commons/funnel-progress-section.tsx
  src/components/ui/form.tsx
Labels: 🎨 Design, 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#190 Feature/#180 레이아웃 컴포넌트 디자인 QA 반영
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/update-password/layout.tsx
  src/app/(client)/meal/post/layout.tsx
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/report/layout.tsx
  src/app/(client)/set-goal/layout.tsx
  src/app/(home)/layout.tsx
  src/components/layouts/global-navigation-bar/index.tsx
  src/components/layouts/header/header-wrapper.tsx
  src/components/layouts/header/index.tsx
  src/components/layouts/header/variants/back-button.tsx
  src/components/layouts/header/variants/default.tsx
  src/components/layouts/header/variants/header-back-button.tsx
  src/components/layouts/header/variants/header-default.tsx
  src/components/layouts/header/variants/with-profile.tsx
  tailwind.config.ts
Labels: 🎨 Design, 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#194 Refactor/#193 rename sentry dev
  next.config.mjs
  src/lib/sentry.ts
Labels: 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#202 Design/#191 목표 설정 pc 반응형
  src/app/(client)/set-goal/components/step-activity-level.tsx
  src/app/(client)/set-goal/components/step-age.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/components/step-gender.tsx
  src/app/(client)/set-goal/components/step-height.tsx
  src/app/(client)/set-goal/components/step-purpose.tsx
  src/app/(client)/set-goal/components/step-weight.tsx
  src/app/(client)/set-goal/layout.tsx
  src/app/(client)/set-goal/page.tsx
Labels: 🎨 Design, ✅ 리뷰 완료

#206 Feature/#203 도넛 그래프 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/commons/macronutrient-pie-chart.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
Labels: ✨ Feature, 🎨 Design, 💌 리뷰 필요

#192 Refactor/#183 식단기록페이지 디자인qa 코드리팩토링
  src/apis/gemini.api.ts
  src/app/(client)/meal/components/meal-images-carousel.tsx
  src/app/(client)/meal/post/components/restore-analysis-modal.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/meal/post/edit/components/ai-loader-without-bg.tsx
  src/app/(client)/meal/post/edit/components/edit-card.tsx
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/edit/components/time-picker.tsx
  src/app/(client)/meal/post/edit/page.tsx
  src/app/(client)/meal/post/hooks/use-restore-analysis-modal.ts
  src/app/(client)/meal/post/layout.tsx
  src/app/(client)/meal/post/page.tsx
  src/app/globals.css
  src/components/commons/macronutrient-box.tsx
  src/utils/format.util.ts
Labels: 🎨 Design, 🔨 Refactor, ✅ 리뷰 완료

#207 Feature/#203 도넛 그래프 컴포넌트 구현
  src/components/commons/macronutrient-pie-chart.tsx
Labels: 🔨 Refactor, 💌 리뷰 필요

#205 Design/#201 sign in pc page
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
Labels: 🎨 Design, 💌 리뷰 필요

#200 Design/#189 home pc design
  public/illustrations/career.svg
  src/apis/meal.api.ts
  src/app/(home)/components/app-use-summary/auth-user-summary.tsx
  src/app/(home)/components/app-use-summary/index.tsx
  src/app/(home)/components/home-calendar/date-selector-mobile.tsx
  src/app/(home)/components/home-calendar/date-selector-pc.tsx
  src/app/(home)/components/home-calendar/home-calendar-client-view.tsx
  src/app/(home)/components/home-calendar/home-calendar-month.tsx
  src/app/(home)/components/home-calendar/home-calendar-server-view.tsx
  src/app/(home)/components/home-calendar/home-calendar-week-item.tsx
  src/app/(home)/components/home-calendar/home-calendar-week.tsx
  src/app/(home)/components/home-content.tsx
  src/app/(home)/components/macronutrient-group.tsx
  src/app/(home)/components/scrollbar-container.tsx
  src/app/(home)/constants/calendar.constant.ts
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/components/commons/responsive.tsx
  src/components/ui/calendar.tsx
  src/hooks/use-is-mobile.ts
  src/middleware.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#218 Bug fix/#217 use funnel rerendering fix
  src/hooks/use-funnel.tsx
Labels: 🐞 BugFix, ✅ 리뷰 완료

#208 Design/#204 sign up page pc
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/commons/glass-background.tsx
Labels: 🎨 Design, ✅ 리뷰 완료

#213 Test/#212 유틸 함수 테스트 코드 작성
  jest.config.js
  package.json
  pnpm-lock.yaml
  src/__tests__/fixtures/camelize.fixture.ts
  src/__tests__/fixtures/format.fixture.ts
  src/__tests__/utils/camelize.util.test.ts
  src/__tests__/utils/cleanup-blob-url.util.test.ts
  src/__tests__/utils/format.util.test.ts
  src/utils/format.util.ts
  tsconfig.json
Labels: ✅ Test, ✅ 리뷰 완료

#210 Feature/#199 ai재분석 음식추가 기능구현
  src/apis/gemini.api.ts
  src/app/(client)/meal/post/components/add-image-form.tsx
  src/app/(client)/meal/post/components/add-image-list.tsx
  src/app/(client)/meal/post/components/add-meal-ai-loading.tsx
  src/app/(client)/meal/post/components/add-meal-drawer.tsx
  src/app/(client)/meal/post/components/meal-post-add-meal-drawer.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/meal/post/edit/components/edit-calendar-drawer.tsx
  src/app/(client)/meal/post/edit/components/edit-card.tsx
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/edit/components/time-picker.tsx
  src/app/(client)/meal/post/edit/constants/meal-edit.constant.ts
  src/app/(client)/meal/post/edit/utils/meal-edit.util.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#224 Feature/#220 add metadata
  public/site-thumbnail.svg
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(client)/meal/post/edit/layout.tsx
  src/app/(client)/meal/post/edit/page.tsx
  src/app/(client)/meal/post/layout.tsx
  src/app/(client)/my-page/layout.tsx
  src/app/(client)/report/layout.tsx
  src/app/(client)/set-goal/layout.tsx
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
Labels: ✨ Feature, 💌 리뷰 필요, 😵 우혁 리뷰중

#227 Feature/#226 사진없이 식사등록
  src/apis/analysis-request.api.ts
  src/app/(client)/meal/components/meal-images-carousel.tsx
  src/app/(client)/meal/post/components/add-image-form.tsx
  src/app/(client)/meal/post/components/add-meal-drawer.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/meal/post/edit/components/add-meal-card-drawer.tsx
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/edit/page.tsx
Labels: ✨ Feature, 💌 리뷰 필요, ✅ 리뷰 완료

#225 Test/#212 유틸 함수 테스트 코드 작성
  src/__tests__/fixtures/environment.fixture.ts
  src/__tests__/fixtures/nutrition-calculator.fixture.ts
  src/__tests__/fixtures/session-storage.fixture.ts
  src/__tests__/utils/nutrition-calculator.util.test.ts
  src/__tests__/utils/predicate.util.test.ts
  src/__tests__/utils/session-storage.util.test.ts
  src/utils/nutrition-calculator.util.ts
Labels: ✅ Test, 💌 리뷰 필요

#228 Feature/#222 리포트 페이지 영양소 관련 그래프
  src/app/(client)/report/apis/fetch-report.api.ts
  src/app/(client)/report/components/calories-amount-report.tsx
  src/app/(client)/report/components/charts.tsx
  src/app/(client)/report/components/macronutrient-amount-box.tsx
  src/app/(client)/report/components/macronutrient-amount-report.tsx
  src/app/(client)/report/components/macronutrient-percentage-box.tsx
  src/app/(client)/report/components/macronutrient-percentage-report.tsx
  src/app/(client)/report/constants/chart.constant.ts
  src/app/(client)/report/constants/unit.constant.ts
  src/app/(client)/report/page.tsx
  src/app/(client)/report/types/chart.type.ts
  src/app/(client)/report/types/nutrition.type.ts
  src/app/(client)/report/utils/nutrition-diff.util.ts
  src/app/api/report/route.ts
  src/components/commons/macronutrient-pie-chart.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#237 Refactor/#236 get percentage 로직 변경
  src/app/(auth)/sign-up/page.tsx
  src/app/(client)/report/utils/nutrition-diff.util.ts
  src/app/(home)/components/calories-summary-card.tsx
  src/app/(home)/components/macronutrient-box.tsx
  src/utils/nutrition-calculator.util.ts
Labels: 🔨 Refactor, ⚠️ ASAP

#234 Feature/#233 header background
  src/components/layouts/header/mobile-header.tsx
  src/components/layouts/header/pc-header.tsx
  src/hooks/use-detect-is-scrolled.ts
Labels: 🎨 Design, 💌 리뷰 필요, ✅ 리뷰 완료

#241 Setting/#240 타이포그래피 반영
  src/app/(auth)/sign-up/components/step-complete.tsx
  src/app/(auth)/sign-up/components/step-email.tsx
  src/app/(auth)/sign-up/components/step-nickname.tsx
  src/app/(auth)/sign-up/components/step-password.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/set-goal/components/step-activity-level.tsx
  src/app/(client)/set-goal/components/step-age.tsx
  src/app/(client)/set-goal/components/step-ai-loading.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/components/step-complete.tsx
  src/app/(client)/set-goal/components/step-gender.tsx
  src/app/(client)/set-goal/components/step-height.tsx
  src/app/(client)/set-goal/components/step-purpose.tsx
  src/app/(client)/set-goal/components/step-weight.tsx
  src/app/(home)/components/app-use-summary/auth-user-summary.tsx
  src/components/commons/macronutrient-pie-chart.tsx
  src/components/ui/typography.tsx
  tailwind.config.ts
Labels: ⚙ Setting, ✅ 리뷰 완료

#214 Design/#209 find password page
  src/apis/auth-server.api.ts
  src/app/(auth)/change-password/components/auth-change-password-form.tsx
  src/app/(auth)/change-password/components/change-password-funnel.tsx
  src/app/(auth)/change-password/components/step-complete.tsx
  src/app/(auth)/change-password/components/step-current-password.tsx
  src/app/(auth)/change-password/components/step-new-password.tsx
  src/app/(auth)/change-password/layout.tsx
  src/app/(auth)/change-password/page.tsx
  src/app/(auth)/change-password/types/funnel-type.ts
  src/app/(auth)/find-password/components/auth-email-form-for-find-password.tsx
  src/app/(auth)/find-password/components/find-password-funnel.tsx
  src/app/(auth)/find-password/components/step-complete.tsx
  src/app/(auth)/find-password/components/step-password.tsx
  src/app/(auth)/find-password/components/step-verifying-email.tsx
  src/app/(auth)/find-password/components/tab-visibility-handler.tsx
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/find-password/types/funnel-type.ts
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-up/components/step-email.tsx
  src/app/(auth)/update-password/components/auth-update-password-form.tsx
  src/app/(auth)/update-password/layout.tsx
  src/app/(auth)/update-password/page.tsx
  src/app/(client)/my-page/components/setting-card.tsx
  src/app/globals.css
  src/components/commons/error-handler.tsx
  src/components/commons/modal.tsx
  src/constants/public-error-message.constant.ts
  src/constants/site-map.constant.ts
  src/middleware.ts
  tailwind.config.ts
Labels: 🎨 Design, 💌 리뷰 필요, ✅ 리뷰 완료

#230 Refactor/#229 마이페이지 리팩토링
  src/app/(client)/my-page/components/edit-profile-drawer.tsx
  src/app/(client)/my-page/components/edit-profile.tsx
  src/app/(client)/my-page/components/profile-bar.tsx
  src/app/(client)/my-page/components/user-goal-card.tsx
  src/app/(client)/my-page/page.tsx
  src/app/(client)/my-page/utils/calculate-macronutrient-ratio.ts
  src/app/(client)/my-page/utils/upload-profile-image.ts
  src/components/commons/profile-image.tsx
Labels: 🔨 Refactor, ✅ 리뷰 완료

#248 Bug fix/#247 use funnel hydration fix
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/components/commons/client-only.tsx
  src/hooks/use-funnel.tsx
  src/hooks/use-is-client.ts
Labels: 🐞 BugFix, ✅ 리뷰 완료

#246 Feature/#239 온보딩 구현
  public/illustrations/onboarding-recommend-img-1.svg
  public/illustrations/onboarding-recommend-img-2.svg
  public/illustrations/onboarding-recommend-img-3.svg
  public/images/onboarding-bg.png
  public/images/onboarding-meal-post-1.png
  public/images/onboarding-meal-post-2.png
  public/images/onboarding-meal-post-3.png
  public/images/onboarding-problem.png
  public/images/onboarding-todayeat-img.png
  src/app/(client)/onboarding/components/cta-card.tsx
  src/app/(client)/onboarding/components/first-section.tsx
  src/app/(client)/onboarding/components/introduce-list.tsx
  src/app/(client)/onboarding/components/recommend-list.tsx
  src/app/(client)/onboarding/components/second-section.tsx
  src/app/(client)/onboarding/components/third-section.tsx
  src/app/(client)/onboarding/layout.tsx
  src/app/(client)/onboarding/page.tsx
  src/constants/site-map.constant.ts
  src/middleware.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#249 Feature/#245 리포트 페이지 수정
  src/app/(client)/report/components/bar-chart-skeleton.tsx
  src/app/(client)/report/components/calories-amount-report.tsx
  src/app/(client)/report/components/charts.tsx
  src/app/(client)/report/components/macronutrient-amount-box.tsx
  src/app/(client)/report/components/macronutrient-amount-report.tsx
  src/app/(client)/report/components/macronutrient-percentage-report.tsx
  src/app/(client)/report/components/pie-chart-skeleton.tsx
  src/app/(client)/report/constants/chart.constant.ts
  src/app/(client)/report/hooks/use-fetch-report.ts
  src/app/api/report/route.ts
  src/app/globals.css
Labels: ✨ Feature, 💌 리뷰 필요

#250 Refactor/#235 목표 설정 리팩토링
  src/app/(client)/set-goal/components/set-goal-funnel.tsx
  src/app/(client)/set-goal/components/step-activity-level.tsx
  src/app/(client)/set-goal/components/step-age.tsx
  src/app/(client)/set-goal/components/step-ai-loading.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/components/step-complete.tsx
  src/app/(client)/set-goal/components/step-gender.tsx
  src/app/(client)/set-goal/components/step-height.tsx
  src/app/(client)/set-goal/components/step-purpose.tsx
  src/app/(client)/set-goal/components/step-weight.tsx
  src/app/(client)/set-goal/hooks/use-client-calculation.ts
  src/app/(client)/set-goal/hooks/use-scroll-to-top.ts
  src/app/(client)/set-goal/page.tsx
  src/app/(client)/set-goal/utils/calculate-macronutrient-data.ts.ts
  src/hooks/use-funnel.tsx
  src/types/DTO/user.dto.ts
Labels: 🔨 Refactor, ✅ 리뷰 완료

#251 Feature/#242 홈페이지 식사기록 편집
  public/icons/close-line-white.svg
  src/apis/meal.api.ts
  src/apis/user.api.ts
  src/app/(home)/components/home-calendar/home-calendar-month-item.tsx
  src/app/(home)/components/home-calendar/home-calendar-month.tsx
  src/app/(home)/components/home-calendar/home-calendar-server-view.tsx
  src/app/(home)/components/home-calendar/home-calendar-week-item.tsx
  src/app/(home)/components/home-calendar/home-calendar-week.tsx
  src/app/(home)/components/home-content.tsx
  src/app/(home)/components/meal-card-container.tsx
  src/app/(home)/components/meal-card.tsx
  src/app/(home)/components/scrollbar-container.tsx
  src/app/(home)/page.tsx
  src/app/api/report/route.ts
  src/types/nutrition.type.ts
  src/utils/date.util.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#253 Feature/#252 게스트 로그인
  public/icons/user-fill.svg
  src/apis/auth-server.api.ts
  src/app/(auth)/sign-in/components/anonymous-sign-in-button.tsx
  src/app/(auth)/sign-in/page.tsx
  src/components/commons/profile-image.tsx
  src/components/layouts/header/variants/with-profile.tsx
  tailwind.config.ts
Labels: ✨ Feature, ✅ 리뷰 완료

#254 Feature/#195 ai analysis modify
  src/apis/analysis-request.api.ts
  src/apis/gemini.api.ts
  src/apis/meal.api.ts
  src/app/(client)/meal/detail/components/total-nutrition-chart.tsx
  src/app/(client)/meal/post/components/add-meal-drawer.tsx
  src/app/(client)/meal/post/components/add-meal-modal.tsx
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/hooks/use-restore-analysis-modal.ts
  src/app/(client)/report/components/macronutrient-percentage-report.tsx
  src/app/(client)/report/page.tsx
  src/app/(home)/components/home-content.tsx
  src/app/(home)/components/macronutrient-group.tsx
  src/app/api/gemini/food-image-analysis/route.ts
  src/app/api/meal-post/route.ts
  src/components/commons/macronutrient-pie-chart.tsx
Labels: ✅ 리뷰 완료

#258 Design/#244 식사수정 pc
  src/app/(client)/meal/components/meal-images-carousel.tsx
  src/app/(client)/meal/detail/components/memo-box.tsx
  src/app/(client)/meal/detail/layout.tsx
  src/app/(client)/meal/post/components/add-meal-drawer.tsx
  src/app/(client)/meal/post/components/add-meal-modal.tsx
  src/app/(client)/meal/post/components/upload-image-section.tsx
  src/app/(client)/meal/post/edit/components/add-meal-card-drawer.tsx
  src/app/(client)/meal/post/edit/components/add-meal-card-pc.tsx
  src/app/(client)/meal/post/edit/components/edit-calendar-pc.tsx
  src/app/(client)/meal/post/edit/components/edit-card.tsx
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/edit/components/time-picker-pc.tsx
  src/app/(client)/meal/post/edit/components/time-picker.tsx
  src/app/(client)/meal/post/edit/constants/error-message.constant.ts
  src/app/(client)/meal/post/layout.tsx
  src/app/(client)/meal/post/utils/revalidate.ts
  src/components/commons/glass-background.tsx
Labels: ✨ Feature, 🎨 Design, ✅ 리뷰 완료

#260 Refactor/#259 탄단지 계산 변경
  src/app/(client)/set-goal/components/macronutrient-box.tsx
  src/app/(client)/set-goal/components/step-calculate.tsx
  src/app/(client)/set-goal/utils/calculate-macronutrient-data.ts.ts
  src/constants/user-personal-info.constant.ts
Labels: 🔨 Refactor, 💌 리뷰 필요, ✅ 리뷰 완료

#261 Feature/#256 로티 프리패치
  public/images/lottie-preview-without-bg.png
  public/images/lottie-preview.png
  src/app/(client)/meal/post/components/add-meal-ai-loading.tsx
  src/app/(client)/meal/post/edit/components/edit-card.tsx
  src/app/(client)/set-goal/components/step-ai-loading.tsx
  src/app/layout.tsx
  src/components/commons/ai-loader-lottie/index.tsx
  src/components/commons/ai-loader-lottie/variant/lottie-for-client-without-bg.tsx
  src/components/commons/ai-loader-lottie/variant/lottie-for-client.tsx
  src/components/commons/ai-loader-lottie/variant/lottie-for-server-without-bg.tsx
  src/components/commons/ai-loader-lottie/variant/lottie-for-server.tsx
Labels: 🔨 Refactor, 💌 리뷰 필요

#264 Refactor/#257 홈페이지 리펙토링
  src/__tests__/utils/camelize.util.test.ts
  src/apis/analysis-request.api.ts
  src/apis/meal.api.ts
  src/apis/user.api.ts
  src/app/(home)/components/home-calendar/date-selector-mobile.tsx
  src/app/(home)/components/home-calendar/date-selector-pc.tsx
  src/app/(home)/components/home-calendar/home-calendar-client-view.tsx
  src/app/(home)/components/home-calendar/home-calendar-month.tsx
  src/app/(home)/components/home-calendar/home-calendar-server-view.tsx
  src/app/(home)/components/home-calendar/home-calendar-week-item.tsx
  src/app/(home)/components/home-calendar/home-calendar-week.tsx
  src/app/(home)/components/home-calendar/index.tsx
  src/app/(home)/components/home-content.tsx
  src/app/(home)/components/macronutrient-box.tsx
  src/app/(home)/components/meal-card-container.tsx
  src/app/(home)/contexts/dashboard.context.tsx
  src/app/(home)/contexts/date.context.tsx
  src/app/(home)/hooks/use-calendar-carousel.ts
  src/app/(home)/hooks/use-date-selector.ts
  src/app/(home)/page.tsx
  src/app/(home)/utils/calendar.util.ts
  src/components/commons/client-only.tsx
  src/utils/camelize.util.ts
Labels: 🔨 Refactor, ✅ 리뷰 완료

#263 Design/#262 detail pc
  src/app/(auth)/change-password/components/change-password-funnel.tsx
  src/app/(auth)/find-password/components/find-password-funnel.tsx
  src/app/(client)/meal/components/meal-calendar-drawer.tsx
  src/app/(client)/meal/components/meal-calendar-pc.tsx
  src/app/(client)/meal/components/time-picker-pc.tsx
  src/app/(client)/meal/components/time-picker.tsx
  src/app/(client)/meal/detail/components/meal-detail-section.tsx
  src/app/(client)/meal/detail/layout.tsx
  src/app/(client)/meal/post/constants/analysis-error.constant.ts
  src/app/(client)/meal/post/edit/components/edit-result-section.tsx
  src/app/(client)/meal/post/edit/constants/error-message.constant.ts
  src/app/(client)/meal/post/edit/utils/time-picker.util.ts
  src/app/(client)/meal/utils/error.util.ts
  src/app/(home)/components/app-use-summary/auth-user-summary.tsx
  src/app/(home)/components/app-use-summary/index.tsx
  src/constants/ai-error-message.constant.ts
  src/utils/date.util.ts
Labels: 🎨 Design, 💌 리뷰 필요

#271 Feature/#270 auth 폴더의 alert를 modal로 변경
  src/app/(auth)/sign-in/_components/sign-in-form.tsx
  src/app/(auth)/sign-up/_components/step-email.tsx
  src/app/(auth)/sign-up/_components/step-nickname.tsx
  src/app/(home)/_components/home-calendar/home-calendar-client-view.tsx
  src/components/commons/client-only.tsx
Labels: ✨ Feature, ✅ 리뷰 완료

#272 Docs/#266 readme 수정
  README.md
Labels: 📃 Docs

#273 Feature/#255 toast 추가
  package.json
  pnpm-lock.yaml
  public/icons/toast-fail.svg
  public/icons/toast-success.svg
  public/images/onboarding-bg.png
  public/images/onboarding-problem.png
  src/app/(client)/meal/[id]/_components/meal-detail-section.tsx
  src/app/(client)/my-page/_components/edit-profile.tsx
  src/app/(client)/my-page/_components/setting-card.tsx
  src/app/(client)/onboarding/_components/first-section.tsx
  src/app/(client)/set-goal/_components/step-calculate.tsx
  src/app/layout.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-funnel.tsx
  src/hooks/use-toast.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, 💌 리뷰 필요

#274 Docs:#266 메인 이미지 및 개발 일정 수정
  README.md
Labels: 📃 Docs, ✅ 리뷰 완료

#276 Design/#275 파비콘 및 썸네일
  public/site-thumbnail.svg
  src/app/icon.ico
  src/app/layout.tsx
Labels: 🎨 Design, 💌 리뷰 필요

#280 Hot fix/#278 onboadring cookie
  src/app/(client)/onboarding/_components/cta-card.tsx
  src/app/(client)/onboarding/_components/first-section.tsx
  src/app/(client)/onboarding/page.tsx
  src/app/(home)/page.tsx
  src/middleware.ts
Labels: ✨ Feature, 💌 리뷰 필요

#281 fix:#279 페이지네이션 위치조정
  src/app/(client)/meal/_components/meal-images-carousel.tsx
Labels: 🐞 BugFix, ⚠️ ASAP

#288 Hot fix/#287 utc date fix
  src/__tests__/fixtures/nutrition-calculator.fixture.ts
  src/app/(client)/meal/_components/meal-calendar-mobile.tsx
  src/app/(client)/meal/_components/meal-calendar-pc.tsx
  src/app/(client)/meal/_utils/file.util.ts
  src/app/(home)/_components/app-use-summary/index.tsx
  src/app/(home)/_components/home-calendar/home-calendar-server-view.tsx
  src/app/(home)/_components/home-calendar/index.tsx
  src/app/(home)/_contexts/date.context.tsx
  src/app/(home)/_hooks/use-calendar-carousel.ts
  src/app/(home)/_utils/calendar.util.ts
  src/app/(home)/page.tsx
  src/app/api/report/route.ts
  src/app/sitemap.ts
  src/middleware.ts
  src/utils/date.util.ts
  src/utils/format.util.ts
Labels: 🐞 BugFix, ⚠️ ASAP

#290 fix:#289 hydration 오류 잡기
  src/app/(home)/_components/home-calendar/home-calendar-server-view.tsx
  src/utils/date.util.ts
Labels: 🐞 BugFix
