Repository llddang/todayeat, pull requests merged in 2025-05, with the labels that each got.

#292 Hotfix:#291 캘린더 날짜 표시 방식 변경
  src/app/(client)/meal/_components/meal-calendar-mobile.tsx
  src/app/(client)/meal/_components/meal-calendar-pc.tsx
Labels: 🐞 BugFix

#294 Bugfix/#293 server time
  src/apis/meal.api.ts
  src/utils/date.util.ts
Labels: 🐞 BugFix, ⚠️ ASAP

#295 Release/v1.0.1
  package.json
  src/apis/meal.api.ts
  src/app/(client)/meal/_components/meal-calendar-mobile.tsx
  src/app/(client)/meal/_components/meal-calendar-pc.tsx
  src/utils/date.util.ts
Labels: 🌏 Deploy

#297 Hot fix/#296 user feedback
  src/app/(client)/meal/_components/meal-calendar-mobile.tsx
  src/app/(client)/meal/_components/meal-calendar-pc.tsx
  src/app/(client)/meal/post/edit/_components/edit-result-section.tsx
  src/app/(client)/set-goal/_components/step-age.tsx
  src/app/(client)/set-goal/_components/step-calculate.tsx
  src/app/(client)/set-goal/_components/step-height.tsx
  src/app/(client)/set-goal/_components/step-weight.tsx
  src/schemas/form-schema.schema.ts
Labels: 🐞 BugFix, ⚠️ ASAP

#299 Hot fix/#298 set goal
  src/app/(client)/set-goal/_components/step-age.tsx
  src/app/(client)/set-goal/_components/step-calculate.tsx
  src/app/(client)/set-goal/_components/step-height.tsx
  src/app/(client)/set-goal/_components/step-weight.tsx
  src/schemas/form-schema.schema.ts
Labels: 🐞 BugFix, ⚠️ ASAP

#301 HotFix/#300 홈 캘린더의 날짜 이슈 해결
  src/app/(client)/meal/_utils/file.util.ts
  src/app/(home)/_components/app-use-summary/index.tsx
  src/app/(home)/_components/home-calendar/home-calendar-client-view.tsx
  src/app/(home)/_components/home-calendar/home-calendar-server-view.tsx
  src/app/(home)/_components/home-calendar/index.tsx
  src/app/(home)/_contexts/date.context.tsx
  src/app/(home)/_utils/calendar.util.ts
  src/app/(home)/page.tsx
  src/app/api/report/route.ts
  src/app/sitemap.ts
Labels: 🐞 BugFix, ⚠️ ASAP
